# Generated by Django 4.2.1 on 2023-06-03 23:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.PositiveIntegerField()),
                ('expiration_date', models.DateField()),
                ('cvc', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('from_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
            ],
        ),
    ]
