# Generated by Django 4.2.1 on 2023-06-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcards', '0003_alter_creditcard_cvc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='cvc',
            field=models.IntegerField(),
        ),
    ]
