# Generated by Django 4.2.1 on 2023-06-04 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('from_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_primary', to=settings.AUTH_USER_MODEL)),
                ('to_account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_secondary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
