# Generated by Django 4.2.1 on 2023-06-04 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='from_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_primary', to='accounts.accounts'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='to_account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_secondary', to='accounts.accounts'),
        ),
    ]
